global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Controls.Primitives;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Markup;
global using System.Windows.Media;

global using CommunityToolkit.Mvvm.Input;
global using JetBrains.Annotations;
global using Microsoft.Win32;
global using Octokit;
global using OneOf;
global using OneOf.Types;
global using Ookii.Dialogs.Wpf;
global using Wpf.Ui.Appearance;
global using Wpf.Ui.Common;

global using Application = System.Windows.Application;
global using Clipboard = Wpf.Ui.Common.Clipboard;
global using MessageBox = Wpf.Ui.Controls.MessageBox;
global using Path = System.IO.Path;
global using RelayCommand = CommunityToolkit.Mvvm.Input.RelayCommand;
